// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bywwhnuicnxbfgbcbrxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5d3dobnVpY254YmZnYmNicnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzMTcyMTIsImV4cCI6MjA4Mzg5MzIxMn0.jNL1dJkBCEGtTnNXYZqGOpLN9tc-ViSOWUgynx1cRIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});